export const downloadService = {
  downloadReceipt: (receiptData, calculations) => {
    const { subtotal, tax, total } = calculations
    
    const receiptText = `
${'='.repeat(50)}
${receiptData.storeName.toUpperCase()}
${receiptData.storeAddress}
Phone: ${receiptData.storePhone}
${'='.repeat(50)}

RECEIPT
Receipt #: ${receiptData.receiptNumber}
Date: ${receiptData.date}

${'='.repeat(50)}
BILL TO:
${receiptData.billTo.name}
${receiptData.billTo.address}
${receiptData.billTo.email}

${'='.repeat(50)}
ITEMS:
${'Item'.padEnd(25)} ${'Qty'.padEnd(5)} ${'Price'.padEnd(8)} ${'Total'.padEnd(8)}
${'-'.repeat(50)}
${receiptData.items.map(item => 
  `${item.name.padEnd(25)} ${item.qty.toString().padEnd(5)} $${item.unitPrice.toFixed(2).padEnd(7)} $${(item.qty * item.unitPrice).toFixed(2)}`
).join('\n')}

${'='.repeat(50)}
SUBTOTAL: $${subtotal.toFixed(2)}
DISCOUNT: $${receiptData.discount.toFixed(2)}
TAX (${receiptData.taxRate}%): $${tax.toFixed(2)}
${'='.repeat(50)}
GRAND TOTAL: $${total.toFixed(2)}
${'='.repeat(50)}

Thank you for your purchase!
Visit us again soon!

Generated by ReceiptGen
    `

    const blob = new Blob([receiptText], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `receipt-${receiptData.receiptNumber}-${receiptData.date}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  },

  downloadPDF: async (receiptData, calculations) => {
    // Future PDF implementation with jsPDF
    console.log('PDF download will be implemented in future version')
  },

  printReceipt: () => {
    window.print()
  }
}